spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:idp-test;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: h2
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: 10m